# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(verbose_name='date booked')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(verbose_name=True)),
                ('v_type', models.CharField(max_length=200)),
                ('license', models.CharField(max_length=200)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.Depot')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Depot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Vehicle'),
        ),
    ]
