# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20171126_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='licence',
            new_name='license',
        ),
    ]
